config/routes.rb
NukeTheCukeRails3::Application.routes.draw do
  resources :steps

  resources :scenarios

  resources :features

  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/feature.rb
class Feature
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :scenarios, type: Array
  field :steps, type: Array
end

app/models/scenario.rb
class Scenario
  include Mongoid::Document
  field :name, type: String
  field :Given, type: String
  field :When, type: String
  field :And, type: String
  field :Then, type: String
  field :variables, type: String
end

app/models/step.rb
class Step
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :code, type: String
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  # GET /features
  # GET /features.json
  def index
    @features = Feature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @features }
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/new
  # GET /features/new.json
  def new
    @feature = Feature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/1/edit
  def edit
    @feature = Feature.find(params[:id])
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(params[:feature])

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render json: @feature, status: :created, location: @feature }
      else
        format.html { render action: "new" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /features/1
  # PUT /features/1.json
  def update
    @feature = Feature.find(params[:id])

    respond_to do |format|
      if @feature.update_attributes(params[:feature])
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to features_url }
      format.json { head :ok }
    end
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  # GET /scenarios
  # GET /scenarios.json
  def index
    @scenarios = Scenario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scenarios }
    end
  end

  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
    @scenario = Scenario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scenario }
    end
  end

  # GET /scenarios/new
  # GET /scenarios/new.json
  def new
    @scenario = Scenario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scenario }
    end
  end

  # GET /scenarios/1/edit
  def edit
    @scenario = Scenario.find(params[:id])
  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    @scenario = Scenario.new(params[:scenario])

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'Scenario was successfully created.' }
        format.json { render json: @scenario, status: :created, location: @scenario }
      else
        format.html { render action: "new" }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scenarios/1
  # PUT /scenarios/1.json
  def update
    @scenario = Scenario.find(params[:id])

    respond_to do |format|
      if @scenario.update_attributes(params[:scenario])
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.json
  def destroy
    @scenario = Scenario.find(params[:id])
    @scenario.destroy

    respond_to do |format|
      format.html { redirect_to scenarios_url }
      format.json { head :ok }
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = Step.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/new
  # GET /steps/new.json
  def new
    @step = Step.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/1/edit
  def edit
    @step = Step.find(params[:id])
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(params[:step])

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render json: @step, status: :created, location: @step }
      else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /steps/1
  # PUT /steps/1.json
  def update
    @step = Step.find(params[:id])

    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step = Step.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to steps_url }
      format.json { head :ok }
    end
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/features/_form.html.erb
<%= form_for(@feature) do |f| %>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :scenario %><br />
    <%= f.text_field :scenario %>
  </div>
  <div class="field">
    <%= f.label :steps %><br />
    <%= f.text_field :steps %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<h1>Listing features</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Scenario</th>
    <th>Steps</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @features.each do |feature| %>
  <tr>
    <td><%= feature.name %></td>
    <td><%= feature.scenario %></td>
    <td><%= feature.steps %></td>
    <td><%= feature.description %></td>
    <td><%= link_to 'Show', feature %></td>
    <td><%= link_to 'Edit', edit_feature_path(feature) %></td>
    <td><%= link_to 'Destroy', feature, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feature', new_feature_path %>

app/views/features/new.html.erb
<h1>New feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @feature.name %>
</p>

<p>
  <b>Scenario:</b>
  <%= @feature.scenario %>
</p>

<p>
  <b>Steps:</b>
  <%= @feature.steps %>
</p>

<p>
  <b>Description:</b>
  <%= @feature.description %>
</p>


<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>

app/views/home/index.html.erb
<h3>Home</h3>
<% @user.each do |user| %>
  <p>User: <%= user.name  %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nuke The Cuke Rails3" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Nuke The Cuke Rails3" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/scenarios/_form.html.erb
<%= form_for(@scenario) do |f| %>
  <% if @scenario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

      <ul>
      <% @scenario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Given %><br />
    <%= f.text_field :Given %>
  </div>
  <div class="field">
    <%= f.label :When %><br />
    <%= f.text_field :When %>
  </div>
  <div class="field">
    <%= f.label :And %><br />
    <%= f.text_field :And %>
  </div>
  <div class="field">
    <%= f.label :Then %><br />
    <%= f.text_field :Then %>
  </div>
  <div class="field">
    <%= f.label :variables %><br />
    <%= f.text_field :variables %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenarios/edit.html.erb
<h1>Editing scenario</h1>

<%= render 'form' %>

<%= link_to 'Show', @scenario %> |
<%= link_to 'Back', scenarios_path %>

app/views/scenarios/index.html.erb
<h1>Listing scenarios</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Given</th>
    <th>When</th>
    <th>And</th>
    <th>Then</th>
    <th>Variables</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scenarios.each do |scenario| %>
  <tr>
    <td><%= scenario.name %></td>
    <td><%= scenario.Given %></td>
    <td><%= scenario.When %></td>
    <td><%= scenario.And %></td>
    <td><%= scenario.Then %></td>
    <td><%= scenario.variables %></td>
    <td><%= link_to 'Show', scenario %></td>
    <td><%= link_to 'Edit', edit_scenario_path(scenario) %></td>
    <td><%= link_to 'Destroy', scenario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scenario', new_scenario_path %>

app/views/scenarios/new.html.erb
<h1>New scenario</h1>

<%= render 'form' %>

<%= link_to 'Back', scenarios_path %>

app/views/scenarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @scenario.name %>
</p>

<p>
  <b>Given:</b>
  <%= @scenario.Given %>
</p>

<p>
  <b>When:</b>
  <%= @scenario.When %>
</p>

<p>
  <b>And:</b>
  <%= @scenario.And %>
</p>

<p>
  <b>Then:</b>
  <%= @scenario.Then %>
</p>

<p>
  <b>Variables:</b>
  <%= @scenario.variables %>
</p>


<%= link_to 'Edit', edit_scenario_path(@scenario) %> |
<%= link_to 'Back', scenarios_path %>

app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @steps.each do |step| %>
  <tr>
    <td><%= step.name %></td>
    <td><%= step.description %></td>
    <td><%= step.code %></td>
    <td><%= link_to 'Show', step %></td>
    <td><%= link_to 'Edit', edit_step_path(step) %></td>
    <td><%= link_to 'Destroy', step, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', steps_path %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @step.name %>
</p>

<p>
  <b>Description:</b>
  <%= @step.description %>
</p>

<p>
  <b>Code:</b>
  <%= @step.code %>
</p>


<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>